server:
  port: 8080
  servlet:
    context-path: /myvettracer

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/myvettracer"
    username: root
    password: 123123123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true


jwt:
  signerKey: "QYfJ0w6aufy3Jaw3zOwIXMCafZm9eRUahVSWPIlBgpgVxNXCYJin7pbsvzhp9ZwX"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds


