server:
  port: 8080
  servlet:
    context-path: /myvettracer

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/myvettracer"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
#  web:
#    cors:
#      allowed-origins: "http://localhost:3000"
#      allowed-methods: "*"
#      allowed-headers: "*"
#      allow-credentials: true



jwt:
  signerKey: "QYfJ0w6aufy3Jaw3zOwIXMCafZm9eRUahVSWPIlBgpgVxNXCYJin7pbsvzhp9ZwX"


