// ? Screens
export const SCREENS = {
  ROOT: "Root",
  HOME: "Home",
  PET: "Pet",
  PROFILE: "Profile",
  LOGIN: "Login",
  TESTSCREEN: "Chat",
  EDITPROFILE: "EditProfile",
  REGISTER: "Register",
  PETDETAIL: "PetDetail",
  EDITPET: "EditPet",
  ADDPET: " AddPet",
  TRACKING : "Tracking",
  VACCINE: " Vaccine",
  ADDVACCINE: " AddVaccine",
  EDITVACCINE: " EditVaccine",
  MEDICINE: "Medicine",
  ADDMEDICINE: " AddMedicine",
  EDITMEDICINE: " EditMedicine",
  APPOINMENT: "Appointment",
  BEFOREADDAPPOINTMENT: "BeforeAddAppointment",
  ADDAPPOINMENT: " AddAppointment",
  EDITAPPOINMENT: " EditAppointment",
  VIEWVETPROFILE:"ViewVetProfile",
  EDITUSERPROFILE: "EditProfile",
  VIEWPET: "ViewPet",
  VIEWOWNERPROFILE: "ViewOwner",
  LISTPET : "Pets"
};
